### PR TITLE
[eve-kernel-arm64-v6.1.38-generic] Enable modules needed for QCOM-based PCIe cellular modems

### PR DESCRIPTION
**Pull request by milan-zededa**
It is more and more common to connect newer high-speed 4G and 5G modems over PCIe rather than over the USB bus.

### CODE REVIEW

**Comment by rucoder** [comment]
@milan-zededa @rene do we have PCI modems on ARM64? do we need this change for ARM?

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by eriknordmark** [comment]
@rucoder Why isn't there a gh action check to build the kernel? Only check is dco.

**Comment by rucoder** [comment]
> @rucoder Why isn't there a gh action check to build the kernel? Only check is dco.

@eriknordmark there is a check to build the kerbel when PR is approved

**Pull request merged**
